kymata-atlas/kymata-core

README.md
invokers/invoker_create_trialwise_data.py
invokers/invoker_estimate_noise_cov_matrix.py
invokers/invoker_run_data_cleansing.py
invokers/invoker_run_hexel_current_estimation.py
invokers/invoker_run_nkg_plotting.py
invokers/run_gridsearch.py
kymata/gridsearch/plain.py
kymata/io/cli.py
kymata/io/logging.py
kymata/preproc/data_cleansing.py
kymata/preproc/hexel_current_estimation.py
kymata/preproc/source.py

Adds timestamped logging to gridsearch (and other) logs for profiling and bughunting.
Fixes #280

Add logging setup to all invokers

---

kymata/entities/expression.py
kymata/plot/layouts.py
kymata/plot/plot.py

Show only chosen sensors

---

kymata/ippm/data_tools.py
kymata/ippm/ippm.py
kymata/ippm/ippm_builder.py
kymata/ippm/ippm_plotter.py
tests/test_ippm_builder.py
tests/test_ippm_data_tools.py
tests/test_ippm_plotter.py

- Refactored plotting and building functionality. The core algorithm remains the same for both but just more modular and easier to read
- Added IPPM class to handle all the config related aspects of IPPM generation to make it simpler to use. 
- Also changed testing philosophy. Now thoroughly test public endpoints instead of both private and public. Aim to get code coverage of 100% still.
To-Dos:
- Refactor causality violation + function recall
- Update builder and plotter to have default config variables (title, figheight, etc). Then, the user can choose to use default (simplest and quickest) or override with a custom config (most specialised for the problem at hand.)
- Documentation for refactored code
- Add some more tests if have time
Will most likely do the doc and tests after paper …

Refactor IPPM Plotter + Builder along with tests

---

kymata/plot/plot.py

Better documentation on minimap view options

Better documentation on minimap view options

---

invokers/run_gridsearch.py
kymata/gridsearch/plain.py
kymata/plot/plot.py

Add the feature to do gridsearch of language functions on TVL functions instead of EMEG data

Kymata language major update

---

invokers/run_gridsearch.py
kymata/gridsearch/plain.py
kymata/io/functions.py
kymata/math/vector.py

Fixes #345 
Basically a bunch of defensive programming to get the gridsearch to go through when it can, or definitively error if it can't

Gridsearch normalize fix

---

kymata/preproc/data_cleansing.py
kymata/preproc/premorph.py
kymata/preproc/source.py

This  PR aims to fix:
- #83 
- #337

Adds eSSS and eeg projection

---

kymata/invokers/invoker_create_trialwise_data.py
kymata/invokers/invoker_estimate_noise_cov_matrix.py
kymata/invokers/invoker_run_data_cleansing.py
kymata/invokers/invoker_run_hexel_current_estimation.py

Fixed the paths of the configuration files in the invokers.

Config path fix

---

demos/demo_plotting.ipynb
kymata/invokers/invoker_run_nkg_plotting.py
kymata/plot/plot.py

141 fix plotting minimap crop

---

kymata/gridsearch/plain.py
kymata/invokers/run_gridsearch.py

Changes milliseconds to seconds in gridsearch

---

kymata/plot/plot.py

Fix axis labels when showing "large" minimap

---

kymata/__init__.py
kymata/entities/__init__.py
kymata/gridsearch/__init__.py
kymata/io/__init__.py
kymata/plot/__init__.py

Import helpers

---

kymata/ippm/ippm.py

We don't actually need to set default here if they're in the actual __init__ default args for the individual strategies

---

demos/demo_ippm.ipynb
kymata/ippm/plot.py

Change default for avoid_collinearity

---

kymata/entities/expression.py
kymata/io/nkg.py
kymata/plot/plot.py

- Bugfix: could not plot expression plots from old nkg files
- Bugfix: layout names not parsed properly
- Bugfix: validation check always failed

🚑️ .nkg hotfix

---

docs/getting-started.md
kymata/io/config.py
kymata/ippm/ippm.py
mkdocs.yml
poetry.lock
pyproject.toml

Improves some docstring stuff and upgrades the mkdocs package

Some docstrings fixes

---

kymata/entities/expression.py

Update warning text

---

codecov.yml
kymata/plot/brain.py
kymata/plot/expression.py
kymata/plot/sensor.py

While doing #485 I also did a little tidying.
~No functional changes.~  #479 seems to block PRs which change untested lines. This is unfeasible for plotting code, so I have configured @codecov to skip plotting code

Small tidy of plotting code

---

kymata/plot/expression.py

Dynamically position α* label on RHS

---

kymata/entities/expression.py
kymata/entities/sparse_data.py
tests/test_expression.py
tests/test_ippm_denoising_strategies_integration_tests.py
tests/test_sparse.py

- Should be a big fix for #388

ExpressionSets are tested for equality using isclose

---

kymata/plot/expression.py

That was an elusive fix!
- Fixes #511

Fix axes resizing when legend is not shown

---

kymata/entities/transform.py
kymata/ippm/evaluation.py
kymata/simulation/signal.py
tests/test_ippm_evaluation.py
tests/test_simulation_signal.py
tests/test_transforms.py

- Adds some helper functions useful for simulations
- Adds a few tests
- Fixes #516
- Fixes #517 
- These fixes revealed #518

A few changes made during IPPM simulation analysis
